"""Auto-generated from the working CRM. Seeds a fresh database (e.g. Postgres) on first run."""

COMPANIES = [{'name': "The Chefs' Warehouse, Inc.",
  'domain': 'chefswarehouse.com',
  'website': 'chefswarehouse.com',
  'description': 'Distributor of specialty food products across the U.S. and Canada, with roughly 50,000 '
                 'SKUs spanning artisan charcuterie, specialty cheeses, oils and vinegars, truffles, caviar, '
                 'and pastry — plus center-of-the-plate custom-cut beef, seafood, and poultry.',
  'city': 'ridgefield',
  'region': 'connecticut',
  'country': 'United States',
  'naics_code': '424420',
  'naics_description': 'Packaged Frozen Food Merchant Wholesalers',
  'employee_range': '1001-5000',
  'revenue_range': '1B-10B',
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '75c385aa24199163eb6cd34ac914d27f'},
 {'name': "Gorton's",
  'domain': 'gortons.com',
  'website': 'gortons.com',
  'description': "One of America's oldest seafood companies (founded 1849), based in Gloucester, MA. A "
                 'frozen-seafood brand with a full line of breaded and battered fish, shrimp, and grilled '
                 'fillets.',
  'city': 'gloucester',
  'region': 'massachusetts',
  'country': 'United States',
  'naics_code': '424420',
  'naics_description': 'Packaged Frozen Food Merchant Wholesalers',
  'employee_range': '201-500',
  'revenue_range': '75M-200M',
  'category': 'Brand / Competitor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '4b751bc7d77713f88bc7c2d855e963a5'},
 {'name': 'Colonna Brothers Inc',
  'domain': 'colonnabrothers.com',
  'website': 'colonnabrothers.com',
  'description': 'Family-owned food distribution company (founded 1918) supplying cheese, sauces, bread '
                 'crumbs, spices, and specialty items to supermarkets, distributors, specialty stores, '
                 'foodservice, and restaurants.',
  'city': 'north bergen',
  'region': 'new jersey',
  'country': 'United States',
  'naics_code': '424420',
  'naics_description': 'Packaged Frozen Food Merchant Wholesalers',
  'employee_range': '201-500',
  'revenue_range': '25M-75M',
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '8f9578b971c2a3ae446181ecd9f70b09'},
 {'name': 'CP Food Products',
  'domain': 'cpfoodsusa.com',
  'website': 'cpfoodsusa.com',
  'description': 'Global supplier of shrimp, value-added shrimp, and ready-made seafood products to '
                 'retailers, restaurant chains, manufacturers, broadline distributors, and cruise lines — '
                 'building customized programs around customer needs.',
  'city': 'columbia',
  'region': 'maryland',
  'country': 'United States',
  'naics_code': '424420',
  'naics_description': 'Packaged Frozen Food Merchant Wholesalers',
  'employee_range': '51-200',
  'revenue_range': '25M-75M',
  'category': 'Brand / Private-label',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '8b74a56f37c344764dabefd938763bef'},
 {'name': 'Big Blue Ocean LLC',
  'domain': 'bigblueocean.net',
  'website': 'bigblueocean.net',
  'description': 'Works directly with fishing fleets worldwide to bring tuna and swordfish to U.S. markets, '
                 'distributing from Miami, Maryland, and New York to supermarket processors, foodservice '
                 'operators, wholesalers, and sashimi distributors.',
  'city': 'jericho',
  'region': 'new york',
  'country': 'United States',
  'naics_code': '424460',
  'naics_description': 'Fish and Seafood Merchant Wholesalers',
  'employee_range': '11-50',
  'revenue_range': '10M-25M',
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'df022cf40854692f483c5cfd2b1a96c5'},
 {'name': 'Nafco Wholesale Fish Dealers',
  'domain': 'nafcofish.com',
  'website': 'nafcofish.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'd96a280ea461a06529d02aa9a5a7b9ba'},
 {'name': 'Latina Boulevard Foods',
  'domain': 'latinaboulevardfoods.com',
  'website': 'latinaboulevardfoods.com',
  'description': None,
  'city': 'buffalo',
  'region': 'new york',
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'd986431c437b72397ed485461a93ab9b'},
 {'name': 'Downeast Dayboat',
  'domain': 'downeastdayboat.com',
  'website': 'downeastdayboat.com',
  'description': None,
  'city': 'bath',
  'region': 'maine',
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'b90d37ae7ca09a25cbf40c0c261d8994'},
 {'name': 'Legit Fish',
  'domain': 'legitfish.com',
  'website': 'legitfish.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '64450da76113c4cddae76887cde65902'},
 {'name': 'JFS/Curtze',
  'domain': 'jfsfoods.com',
  'website': 'jfsfoods.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '408d64e8302822464a109027c3895409'},
 {'name': 'Tichon Seafood',
  'domain': 'tichonseafood.com',
  'website': 'tichonseafood.com',
  'description': None,
  'city': 'fairhaven',
  'region': 'massachusetts',
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '96f8f96f89fd4de8c7cab22ed9dfcb80'},
 {'name': 'United Natural Foods (UNFI)',
  'domain': 'unfi.com',
  'website': 'unfi.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'af1a4ea496c2d7d01d9d1ebd8d5c82f4'},
 {'name': 'Acme Smoked Fish',
  'domain': 'acmesmokedfish.com',
  'website': 'acmesmokedfish.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '0d563b3663d3de4665e8e01b1c4f4bbe'},
 {'name': 'Northern Wind',
  'domain': 'northernwind.com',
  'website': 'northernwind.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '8987934faf9236fd5845b8a27adc45fe'},
 {'name': 'Channel Fish Processing',
  'domain': 'channelfish.com',
  'website': 'channelfish.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'ce1a02e0e8fc7e60dc745a62c254bdec'},
 {'name': 'North Coast Seafoods',
  'domain': 'northcoastseafoods.com',
  'website': 'northcoastseafoods.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '73dc09206be2eafc0d665bd031448783'},
 {'name': 'Northern Pelagic Group (Norpel)',
  'domain': 'norpel.com',
  'website': 'norpel.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '28bd21d497643f28a1952be788a8b7be'},
 {'name': 'Sunnyside Fresh',
  'domain': 'sunnysidefresh.com',
  'website': 'sunnysidefresh.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Brand / Private-label',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '18c3b2ce1fad27af85f032aa35273c97'},
 {'name': 'Foodnerd',
  'domain': 'foodnerdinc.com',
  'website': 'foodnerdinc.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Brand / Private-label',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'd46130b679b678e28a75646ceb052e15'},
 {'name': "Zina's Fine Foods",
  'domain': 'zsalads.com',
  'website': 'zsalads.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Brand / Private-label',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'c22a50470f96be6970a982204a1968d5'},
 {'name': 'CFE Seafoods',
  'domain': 'cfeseafoods.com',
  'website': 'cfeseafoods.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'f3d9ad0e91a9c80eaa6028ea8270b377'},
 {'name': 'Porky Products',
  'domain': 'porky.com',
  'website': 'porky.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '3f2446231f492e4ead1eeb1669f03497'},
 {'name': 'Sea Watch International',
  'domain': 'seawatch.com',
  'website': 'seawatch.com',
  'description': None,
  'city': None,
  'region': None,
  'country': 'United States',
  'naics_code': None,
  'naics_description': None,
  'employee_range': None,
  'revenue_range': None,
  'category': 'Distributor',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '1a783614cf1188b4b373aa80e634efba'}]

CONTACTS = [{'first_name': 'K.C.',
  'last_name': 'Boyle',
  'full_name': 'K.C. Boyle',
  'title': 'Vice President of Seafood',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAOX3EcB_Ntua5v8MuApyeFfkoyFR6KETeo',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'd36583d3433f0c32552767d86975f86c11545396',
  'company_key': '75c385aa24199163eb6cd34ac914d27f'},
 {'first_name': 'Howard',
  'last_name': 'Cai',
  'full_name': 'Howard Cai',
  'title': 'EVP & Acting President',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAABNg5kB8FNwJEPFppq1YUioMcnvUzweMWo',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '62bd85bfe22f64d1e4b05c5ec2bf7c5dbdf84fd1',
  'company_key': '8b74a56f37c344764dabefd938763bef'},
 {'first_name': 'Jake',
  'last_name': 'Holbrook',
  'full_name': 'Jake Holbrook',
  'title': 'VP of Marketing',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAVyzggBNREgBIstOt7LW3xP97Q4xzlCqF0',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'f1e734ee112fce7b24e7ac4e10c9afc3d13859fe',
  'company_key': '4b751bc7d77713f88bc7c2d855e963a5'},
 {'first_name': 'Alberto',
  'last_name': 'Valenzuela',
  'full_name': 'Alberto Valenzuela',
  'title': 'VP of Business Development',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAANHAS0BhfeHrvuy40jkZFUer3lSCkm65II',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '80601762f3ad1865658cb23ae2944d064de4b886',
  'company_key': 'd96a280ea461a06529d02aa9a5a7b9ba'},
 {'first_name': 'Albert',
  'last_name': 'Disteso',
  'full_name': 'Albert Disteso',
  'title': 'VP of Sales',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAd4Ld8B393c1HvQ9BvTIgY9pbSqf9X6vLk',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '58c904045de8b12a1e30d3e7bf34727498f0560b',
  'company_key': '8f9578b971c2a3ae446181ecd9f70b09'},
 {'first_name': 'Jane',
  'last_name': 'Grimaldi',
  'full_name': 'Jane Grimaldi',
  'title': 'Procurement',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAUDrmUBWmKtD5YLG0EgszuO-Qeor2-m90Q',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'cb570dccadf19271e20d00e3c7d460e26aeebf99',
  'company_key': 'd986431c437b72397ed485461a93ab9b'},
 {'first_name': 'Togue',
  'last_name': 'Brawn',
  'full_name': 'Togue Brawn',
  'title': 'Owner / Founder',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAjfHlcBLEpbmlm3Kdx20j3zUfFoIbey2KQ',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'd3925f2c54e5c7dd89b07afd4651950dbdce7f4e',
  'company_key': 'b90d37ae7ca09a25cbf40c0c261d8994'},
 {'first_name': 'Philip',
  'last_name': 'Walsh',
  'full_name': 'Philip Walsh',
  'title': 'VP of Sales',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAADe-ar0BvGN8i0qIEFK8ETN2fS0GyTxy-qc',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'd92eca30f6c97afc5e43156d7b01c24630d1164c',
  'company_key': '64450da76113c4cddae76887cde65902'},
 {'first_name': 'Stefanie',
  'last_name': 'Gage',
  'full_name': 'Stefanie Gage',
  'title': 'Purchasing Assistant',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAABfYIVwB-tum3-tGdniG3-7yreiO2ZrjZPc',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '2862f4c6daf89ee261d26f25defe58daec9b1b1d',
  'company_key': '408d64e8302822464a109027c3895409'},
 {'first_name': 'Jennifer',
  'last_name': 'Tichon',
  'full_name': 'Jennifer Tichon',
  'title': 'Executive Vice President',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAlQ8GABXJ9f3XIu7WE3050eXK89qfFJuJU',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '23616ed592d0a96227b31a4bbaa10024c30a1ec3',
  'company_key': '96f8f96f89fd4de8c7cab22ed9dfcb80'},
 {'first_name': 'David',
  'last_name': 'Vermilyea',
  'full_name': 'David Vermilyea',
  'title': 'Buyer',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAABrldbEBDtrf4zA_iQ512XWp1hJ5Q0JMgd0',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'c062294de2ccaca3539b0eab1937b757ac731466',
  'company_key': '75c385aa24199163eb6cd34ac914d27f'},
 {'first_name': 'Angela',
  'last_name': 'Ichwan',
  'full_name': 'Angela Ichwan',
  'title': 'VP of R&D and FSQA',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAADb4MBZIFc9PCpTImDtJ82FAfK_sN2tlE',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'b19406ec20ea6ec8f2240eabaf4ad7a17c7aeb4a',
  'company_key': '4b751bc7d77713f88bc7c2d855e963a5'},
 {'first_name': 'Joshua',
  'last_name': 'Guenther',
  'full_name': 'Joshua Guenther',
  'title': 'VP, Marketing / Corporate Development',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAmuVrwBsURS4xkPtCh1WfR1zXP3usQJrWw',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '22400554b1e2b06e3f54fde1655d8e731f17cded',
  'company_key': 'd986431c437b72397ed485461a93ab9b'},
 {'first_name': 'Nick',
  'last_name': 'Simonson',
  'full_name': 'Nick Simonson',
  'title': 'Replenishment Buyer',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAABu3C6ABtB2atHSlRu6PAtApugVPXh9Y3UI',
  'status': 'prospect',
  'source': 'explorium',
  'external_id': 'a93181556616920a7d7e4393c53b6ab3cef093b9',
  'company_key': 'af1a4ea496c2d7d01d9d1ebd8d5c82f4'},
 {'first_name': 'Aaron',
  'last_name': 'Katz',
  'full_name': 'Aaron Katz',
  'title': 'Regional GM, Protein Division',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAABImaEsBsRJfCCy3MD31Ns6KbczSw_r0NVM',
  'status': 'prospect',
  'source': 'explorium',
  'external_id': '7b349ba469ee25c3f1969e78ef6922d2828e7c07',
  'company_key': '75c385aa24199163eb6cd34ac914d27f'},
 {'first_name': 'Ed',
  'last_name': 'Leppien',
  'full_name': 'Ed Leppien',
  'title': 'Director of Sales',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAACbnV8BDlwBNFo8A48YuCVM7We8QcJrq3w',
  'status': 'prospect',
  'source': 'explorium',
  'external_id': 'f036f4c317257af91eaeb43a0f401b8ea4c9fc85',
  'company_key': 'd986431c437b72397ed485461a93ab9b'},
 {'first_name': 'James',
  'last_name': 'M.',
  'full_name': 'James M.',
  'title': 'Procurement Manager',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAEe4LOgBQ2mSfb6C-PBRojoLLJGZQFCuWmM',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '5a8c046c84d63c99e67ebbb58229a52a6cd3677e',
  'company_key': '8987934faf9236fd5845b8a27adc45fe'},
 {'first_name': 'Ian',
  'last_name': 'White',
  'full_name': 'Ian White',
  'title': 'VP Business Development',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAjYlh4BpBmAdL0cAPIRflrYhNXE9v1RrKg',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'caa59c6e5f88f5f1292faa444505e31d6496102d',
  'company_key': 'ce1a02e0e8fc7e60dc745a62c254bdec'},
 {'first_name': 'Casey',
  'last_name': 'King',
  'full_name': 'Casey King',
  'title': 'Purchasing Manager',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAD48vk4Bt66T0oB7iAxkkWr2aMk8RBmyT7A',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '63473ebe66a5ef0eea4252c9dec2eef83bd7c623',
  'company_key': '73dc09206be2eafc0d665bd031448783'},
 {'first_name': 'Andre',
  'last_name': 'Minnaar',
  'full_name': 'Andre Minnaar',
  'title': 'VP Innovation & Quality',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAOEu84Bs_nJAL5DEEE8OPl3GwjE4C19ulg',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'd3b0691921fc84d217611cb3c8ee4b0dd79c3786',
  'company_key': '28bd21d497643f28a1952be788a8b7be'},
 {'first_name': 'Frank',
  'last_name': 'Tedesco',
  'full_name': 'Frank Tedesco',
  'title': 'Chief Executive Officer',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAPdrckB09rd1sewQnsUubeN141Mkygeu2U',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '826791c7ec44df206b537524087e3631d1562bf8',
  'company_key': '18c3b2ce1fad27af85f032aa35273c97'},
 {'first_name': 'Sharon',
  'last_name': 'Cryan',
  'full_name': 'Sharon Cryan',
  'title': 'Founder & CEO',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAABA_8_gBLRBfYAmBfFdaFSPuA81Ty5nURA0',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'ac48a5d12c196f60eb6f512f3d1a824d74179e94',
  'company_key': 'd46130b679b678e28a75646ceb052e15'},
 {'first_name': 'Alex',
  'last_name': 'Chenakal',
  'full_name': 'Alex Chenakal',
  'title': 'Vice President',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAA1_SEcBvsbDbbjol607MH0UJi8KRPG2wU0',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'fd5d0af8a5fd24a02f1255445fd27310dceaca31',
  'company_key': 'c22a50470f96be6970a982204a1968d5'},
 {'first_name': 'Frank',
  'last_name': 'Carideo',
  'full_name': 'Frank Carideo',
  'title': 'VP Sales',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAD4Z8wBJ5lpVk0rjkIAKwrHOTEQNQIgNkk',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '6db11a5d57259f50332cf0d7cb0e8380cdf1a895',
  'company_key': 'f3d9ad0e91a9c80eaa6028ea8270b377'},
 {'first_name': 'Andrew',
  'last_name': 'Fabiano',
  'full_name': 'Andrew Fabiano',
  'title': 'Buyer',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAADfdwAQB4Zj7LtDG8nq2ag-ENwG2Yr0--ss',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'df8429fda1ec838042b4e8cf7cf29c52061db57c',
  'company_key': '3f2446231f492e4ead1eeb1669f03497'},
 {'first_name': 'Jennifer',
  'last_name': 'Sussman',
  'full_name': 'Jennifer Sussman',
  'title': 'VP Category Management',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAEkqYwB1HQ74ClRhrX8JjrzuexWr4hbI3Y',
  'status': 'lead',
  'source': 'explorium',
  'external_id': 'e9c5f2412d55d3aeee3b49e199622c72efa36b97',
  'company_key': '75c385aa24199163eb6cd34ac914d27f'},
 {'first_name': 'Michael',
  'last_name': 'Carroll',
  'full_name': 'Michael Carroll',
  'title': 'Founder & CEO',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAESHw4BJmdTkmCF7Gk_ptxM_NewXEyTFyA',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '2879108e651b6f384ebe540ab085663115bf6e5a',
  'company_key': '64450da76113c4cddae76887cde65902'},
 {'first_name': 'Sam',
  'last_name': 'Lustberg',
  'full_name': 'Sam Lustberg',
  'title': 'Sr. Project Manager, Growth & Ops',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAACQSAlMBZAyRLbyk6tyPwh8pGqQzwne6utM',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '0f3e5a80cd37887d44aaff91e9df4786a4988982',
  'company_key': '0d563b3663d3de4665e8e01b1c4f4bbe'},
 {'first_name': 'Patrick',
  'last_name': 'Ginley',
  'full_name': 'Patrick Ginley',
  'title': 'Sales',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAb4zGoBxywQz8zmgac9tnnzyFXW2M2mm7Y',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '6339af2a3343bc0c52a8d991c2960827b541814e',
  'company_key': '73dc09206be2eafc0d665bd031448783'},
 {'first_name': 'Mariann',
  'last_name': 'Miller',
  'full_name': 'Mariann Miller',
  'title': 'Regional Account Manager',
  'job_level': None,
  'department': None,
  'email': None,
  'phone': None,
  'linkedin': 'linkedin.com/in/ACoAAAtU_HwBLi56oeETFxqBupYm3CEVzJC05V8',
  'status': 'lead',
  'source': 'explorium',
  'external_id': '234c5556d5f37105677ecf1e86b69360fb0ef578',
  'company_key': '1a783614cf1188b4b373aa80e634efba'}]
